volumes:
  app-data:
    driver: local
services:
  app-redis:
    image: docker.io/redis:6
    healthcheck:
      test: redis-cli ping
      interval: 5s
      timeout: 1s
      retries: 5
  app-postgres:
    image: docker.io/postgres:16
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - app-data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U postgres
      start_period: 10s
      timeout: 1s
      retries: 5
      interval: 5s
  research-api-debug:
    image: research-agent-debug
    build:
      context: .
      dockerfile: Dockerfile.debug
    ports:
      - "8123:8000"
      # Maps port 5678 on your local machine to port 5678 in the container (for the debugger).
      - "5678:5678"
    depends_on:
      app-redis:
        condition: service_healthy
      app-postgres:
        condition: service_healthy
    environment:
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      LANGSMITH_API_KEY: ${LANGSMITH_API_KEY}
      REDIS_URI: redis://app-redis:6379
      POSTGRES_URI: postgres://postgres:postgres@app-postgres:5432/postgres?sslmode=disable
      DEBUG_MODE: true
      DEBUG_PORT: 5678
